# Generated by Django 6.0.6 on 2026-07-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='resource_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('article', 'Article'), ('interactive', 'Interactive')], max_length=20),
        ),
    ]
