# Generated by Django 6.0.6 on 2026-06-25 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='knowledge_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.knowledgearea'),
        ),
    ]
