# Generated by Django 6.0.6 on 2026-06-25 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.knowledgearea')),
            ],
        ),
    ]
