# Generated by Django 6.0.6 on 2026-07-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_gaps', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgegap',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgegap',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=20),
        ),
    ]
